# Generated by Django 4.1.7 on 2024-10-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BdOSN', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maslab',
            name='booked_by',
            field=models.CharField(default='not specified', max_length=100),
        ),
    ]
